export const GET_TOURNAMENTS_START = "tournaments@GET_TOURNAMENTS_REQUEST"
export const GET_TOURNAMENTS_SUCCESS = "tournaments@GET_TOURNAMENTS_SUCCESS"
export const GET_TOURNAMENTS_FAILURE = "tournaments@GET_TOURNAMENTS_FAILURE"
